# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: object=None, links: object=None, meta: object=None):  # noqa: E501
        """Error - a model defined in Swagger

        :param status: The status of this Error.  # noqa: E501
        :type status: str
        :param message: The message of this Error.  # noqa: E501
        :type message: str
        :param data: The data of this Error.  # noqa: E501
        :type data: object
        :param links: The links of this Error.  # noqa: E501
        :type links: object
        :param meta: The meta of this Error.  # noqa: E501
        :type meta: object
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': object,
            'links': object,
            'meta': object
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this Error.


        :return: The status of this Error.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Error.


        :param status: The status of this Error.
        :type status: str
        """
        allowed_values = ["error"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this Error.


        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Error.


        :param message: The message of this Error.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def data(self) -> object:
        """Gets the data of this Error.


        :return: The data of this Error.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Error.


        :param data: The data of this Error.
        :type data: object
        """

        self._data = data

    @property
    def links(self) -> object:
        """Gets the links of this Error.


        :return: The links of this Error.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links: object):
        """Sets the links of this Error.


        :param links: The links of this Error.
        :type links: object
        """

        self._links = links

    @property
    def meta(self) -> object:
        """Gets the meta of this Error.


        :return: The meta of this Error.
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta: object):
        """Sets the meta of this Error.


        :param meta: The meta of this Error.
        :type meta: object
        """

        self._meta = meta
