# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2005_links import InlineResponse2005Links  # noqa: F401,E501
from swagger_server.models.inline_response2005_meta import InlineResponse2005Meta  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: Product=None, links: InlineResponse2005Links=None, meta: InlineResponse2005Meta=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param status: The status of this InlineResponse2005.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse2005.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse2005.  # noqa: E501
        :type data: Product
        :param links: The links of this InlineResponse2005.  # noqa: E501
        :type links: InlineResponse2005Links
        :param meta: The meta of this InlineResponse2005.  # noqa: E501
        :type meta: InlineResponse2005Meta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': Product,
            'links': InlineResponse2005Links,
            'meta': InlineResponse2005Meta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse2005.


        :return: The status of this InlineResponse2005.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse2005.


        :param status: The status of this InlineResponse2005.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2005.


        :return: The message of this InlineResponse2005.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2005.


        :param message: The message of this InlineResponse2005.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Product:
        """Gets the data of this InlineResponse2005.


        :return: The data of this InlineResponse2005.
        :rtype: Product
        """
        return self._data

    @data.setter
    def data(self, data: Product):
        """Sets the data of this InlineResponse2005.


        :param data: The data of this InlineResponse2005.
        :type data: Product
        """

        self._data = data

    @property
    def links(self) -> InlineResponse2005Links:
        """Gets the links of this InlineResponse2005.


        :return: The links of this InlineResponse2005.
        :rtype: InlineResponse2005Links
        """
        return self._links

    @links.setter
    def links(self, links: InlineResponse2005Links):
        """Sets the links of this InlineResponse2005.


        :param links: The links of this InlineResponse2005.
        :type links: InlineResponse2005Links
        """

        self._links = links

    @property
    def meta(self) -> InlineResponse2005Meta:
        """Gets the meta of this InlineResponse2005.


        :return: The meta of this InlineResponse2005.
        :rtype: InlineResponse2005Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: InlineResponse2005Meta):
        """Sets the meta of this InlineResponse2005.


        :param meta: The meta of this InlineResponse2005.
        :type meta: InlineResponse2005Meta
        """

        self._meta = meta
