# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, category: str=None, count: int=None):  # noqa: E501
        """InlineResponse2006Data - a model defined in Swagger

        :param category: The category of this InlineResponse2006Data.  # noqa: E501
        :type category: str
        :param count: The count of this InlineResponse2006Data.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {
            'category': str,
            'count': int
        }

        self.attribute_map = {
            'category': 'category',
            'count': 'count'
        }
        self._category = category
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6_data of this InlineResponse2006Data.  # noqa: E501
        :rtype: InlineResponse2006Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this InlineResponse2006Data.


        :return: The category of this InlineResponse2006Data.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this InlineResponse2006Data.


        :param category: The category of this InlineResponse2006Data.
        :type category: str
        """

        self._category = category

    @property
    def count(self) -> int:
        """Gets the count of this InlineResponse2006Data.

        Number of products in this category  # noqa: E501

        :return: The count of this InlineResponse2006Data.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this InlineResponse2006Data.

        Number of products in this category  # noqa: E501

        :param count: The count of this InlineResponse2006Data.
        :type count: int
        """

        self._count = count
