# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class InlineResponse200Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: Link=None, login: Link=None, products: Link=None):  # noqa: E501
        """InlineResponse200Links - a model defined in Swagger

        :param _self: The _self of this InlineResponse200Links.  # noqa: E501
        :type _self: Link
        :param login: The login of this InlineResponse200Links.  # noqa: E501
        :type login: Link
        :param products: The products of this InlineResponse200Links.  # noqa: E501
        :type products: Link
        """
        self.swagger_types = {
            '_self': Link,
            'login': Link,
            'products': Link
        }

        self.attribute_map = {
            '_self': 'self',
            'login': 'login',
            'products': 'products'
        }
        self.__self = _self
        self._login = login
        self._products = products

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_links of this InlineResponse200Links.  # noqa: E501
        :rtype: InlineResponse200Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> Link:
        """Gets the _self of this InlineResponse200Links.


        :return: The _self of this InlineResponse200Links.
        :rtype: Link
        """
        return self.__self

    @_self.setter
    def _self(self, _self: Link):
        """Sets the _self of this InlineResponse200Links.


        :param _self: The _self of this InlineResponse200Links.
        :type _self: Link
        """

        self.__self = _self

    @property
    def login(self) -> Link:
        """Gets the login of this InlineResponse200Links.


        :return: The login of this InlineResponse200Links.
        :rtype: Link
        """
        return self._login

    @login.setter
    def login(self, login: Link):
        """Sets the login of this InlineResponse200Links.


        :param login: The login of this InlineResponse200Links.
        :type login: Link
        """

        self._login = login

    @property
    def products(self) -> Link:
        """Gets the products of this InlineResponse200Links.


        :return: The products of this InlineResponse200Links.
        :rtype: Link
        """
        return self._products

    @products.setter
    def products(self, products: Link):
        """Sets the products of this InlineResponse200Links.


        :param products: The products of this InlineResponse200Links.
        :type products: Link
        """

        self._products = products
