# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token_expires_at: datetime=None, timestamp: datetime=None):  # noqa: E501
        """InlineResponse2002Meta - a model defined in Swagger

        :param token_expires_at: The token_expires_at of this InlineResponse2002Meta.  # noqa: E501
        :type token_expires_at: datetime
        :param timestamp: The timestamp of this InlineResponse2002Meta.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'token_expires_at': datetime,
            'timestamp': datetime
        }

        self.attribute_map = {
            'token_expires_at': 'token_expires_at',
            'timestamp': 'timestamp'
        }
        self._token_expires_at = token_expires_at
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_meta of this InlineResponse2002Meta.  # noqa: E501
        :rtype: InlineResponse2002Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token_expires_at(self) -> datetime:
        """Gets the token_expires_at of this InlineResponse2002Meta.


        :return: The token_expires_at of this InlineResponse2002Meta.
        :rtype: datetime
        """
        return self._token_expires_at

    @token_expires_at.setter
    def token_expires_at(self, token_expires_at: datetime):
        """Sets the token_expires_at of this InlineResponse2002Meta.


        :param token_expires_at: The token_expires_at of this InlineResponse2002Meta.
        :type token_expires_at: datetime
        """

        self._token_expires_at = token_expires_at

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this InlineResponse2002Meta.


        :return: The timestamp of this InlineResponse2002Meta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this InlineResponse2002Meta.


        :param timestamp: The timestamp of this InlineResponse2002Meta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
