# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, links: object=None, meta: object=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse2001.  # noqa: E501
        :type message: str
        :param links: The links of this InlineResponse2001.  # noqa: E501
        :type links: object
        :param meta: The meta of this InlineResponse2001.  # noqa: E501
        :type meta: object
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'links': object,
            'meta': object
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse2001.


        :return: The status of this InlineResponse2001.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse2001.


        :param status: The status of this InlineResponse2001.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2001.


        :return: The message of this InlineResponse2001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2001.


        :param message: The message of this InlineResponse2001.
        :type message: str
        """

        self._message = message

    @property
    def links(self) -> object:
        """Gets the links of this InlineResponse2001.


        :return: The links of this InlineResponse2001.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links: object):
        """Sets the links of this InlineResponse2001.


        :param links: The links of this InlineResponse2001.
        :type links: object
        """

        self._links = links

    @property
    def meta(self) -> object:
        """Gets the meta of this InlineResponse2001.


        :return: The meta of this InlineResponse2001.
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta: object):
        """Sets the meta of this InlineResponse2001.


        :param meta: The meta of this InlineResponse2001.
        :type meta: object
        """

        self._meta = meta
