# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_categories: int=None, timestamp: datetime=None):  # noqa: E501
        """InlineResponse2006Meta - a model defined in Swagger

        :param total_categories: The total_categories of this InlineResponse2006Meta.  # noqa: E501
        :type total_categories: int
        :param timestamp: The timestamp of this InlineResponse2006Meta.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'total_categories': int,
            'timestamp': datetime
        }

        self.attribute_map = {
            'total_categories': 'total_categories',
            'timestamp': 'timestamp'
        }
        self._total_categories = total_categories
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6_meta of this InlineResponse2006Meta.  # noqa: E501
        :rtype: InlineResponse2006Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_categories(self) -> int:
        """Gets the total_categories of this InlineResponse2006Meta.


        :return: The total_categories of this InlineResponse2006Meta.
        :rtype: int
        """
        return self._total_categories

    @total_categories.setter
    def total_categories(self, total_categories: int):
        """Sets the total_categories of this InlineResponse2006Meta.


        :param total_categories: The total_categories of this InlineResponse2006Meta.
        :type total_categories: int
        """

        self._total_categories = total_categories

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this InlineResponse2006Meta.


        :return: The timestamp of this InlineResponse2006Meta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this InlineResponse2006Meta.


        :param timestamp: The timestamp of this InlineResponse2006Meta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
