# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2006_data import InlineResponse2006Data  # noqa: F401,E501
from swagger_server.models.inline_response2006_meta import InlineResponse2006Meta  # noqa: F401,E501
from swagger_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: List[InlineResponse2006Data]=None, links: object=None, meta: InlineResponse2006Meta=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param status: The status of this InlineResponse2006.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse2006.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse2006.  # noqa: E501
        :type data: List[InlineResponse2006Data]
        :param links: The links of this InlineResponse2006.  # noqa: E501
        :type links: object
        :param meta: The meta of this InlineResponse2006.  # noqa: E501
        :type meta: InlineResponse2006Meta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': List[InlineResponse2006Data],
            'links': object,
            'meta': InlineResponse2006Meta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse2006.


        :return: The status of this InlineResponse2006.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse2006.


        :param status: The status of this InlineResponse2006.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2006.


        :return: The message of this InlineResponse2006.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2006.


        :param message: The message of this InlineResponse2006.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[InlineResponse2006Data]:
        """Gets the data of this InlineResponse2006.


        :return: The data of this InlineResponse2006.
        :rtype: List[InlineResponse2006Data]
        """
        return self._data

    @data.setter
    def data(self, data: List[InlineResponse2006Data]):
        """Sets the data of this InlineResponse2006.


        :param data: The data of this InlineResponse2006.
        :type data: List[InlineResponse2006Data]
        """

        self._data = data

    @property
    def links(self) -> object:
        """Gets the links of this InlineResponse2006.


        :return: The links of this InlineResponse2006.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links: object):
        """Sets the links of this InlineResponse2006.


        :param links: The links of this InlineResponse2006.
        :type links: object
        """

        self._links = links

    @property
    def meta(self) -> InlineResponse2006Meta:
        """Gets the meta of this InlineResponse2006.


        :return: The meta of this InlineResponse2006.
        :rtype: InlineResponse2006Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: InlineResponse2006Meta):
        """Sets the meta of this InlineResponse2006.


        :param meta: The meta of this InlineResponse2006.
        :type meta: InlineResponse2006Meta
        """

        self._meta = meta
