# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_at: datetime=None, created_by: str=None):  # noqa: E501
        """InlineResponse201Meta - a model defined in Swagger

        :param created_at: The created_at of this InlineResponse201Meta.  # noqa: E501
        :type created_at: datetime
        :param created_by: The created_by of this InlineResponse201Meta.  # noqa: E501
        :type created_by: str
        """
        self.swagger_types = {
            'created_at': datetime,
            'created_by': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'created_by': 'created_by'
        }
        self._created_at = created_at
        self._created_by = created_by

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_meta of this InlineResponse201Meta.  # noqa: E501
        :rtype: InlineResponse201Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this InlineResponse201Meta.


        :return: The created_at of this InlineResponse201Meta.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this InlineResponse201Meta.


        :param created_at: The created_at of this InlineResponse201Meta.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self) -> str:
        """Gets the created_by of this InlineResponse201Meta.


        :return: The created_by of this InlineResponse201Meta.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this InlineResponse201Meta.


        :param created_by: The created_by of this InlineResponse201Meta.
        :type created_by: str
        """

        self._created_by = created_by
