# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, deleted_at: datetime=None, deleted_by: str=None):  # noqa: E501
        """InlineResponse2005Meta - a model defined in Swagger

        :param deleted_at: The deleted_at of this InlineResponse2005Meta.  # noqa: E501
        :type deleted_at: datetime
        :param deleted_by: The deleted_by of this InlineResponse2005Meta.  # noqa: E501
        :type deleted_by: str
        """
        self.swagger_types = {
            'deleted_at': datetime,
            'deleted_by': str
        }

        self.attribute_map = {
            'deleted_at': 'deleted_at',
            'deleted_by': 'deleted_by'
        }
        self._deleted_at = deleted_at
        self._deleted_by = deleted_by

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5_meta of this InlineResponse2005Meta.  # noqa: E501
        :rtype: InlineResponse2005Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deleted_at(self) -> datetime:
        """Gets the deleted_at of this InlineResponse2005Meta.


        :return: The deleted_at of this InlineResponse2005Meta.
        :rtype: datetime
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at: datetime):
        """Sets the deleted_at of this InlineResponse2005Meta.


        :param deleted_at: The deleted_at of this InlineResponse2005Meta.
        :type deleted_at: datetime
        """

        self._deleted_at = deleted_at

    @property
    def deleted_by(self) -> str:
        """Gets the deleted_by of this InlineResponse2005Meta.


        :return: The deleted_by of this InlineResponse2005Meta.
        :rtype: str
        """
        return self._deleted_by

    @deleted_by.setter
    def deleted_by(self, deleted_by: str):
        """Sets the deleted_by of this InlineResponse2005Meta.


        :param deleted_by: The deleted_by of this InlineResponse2005Meta.
        :type deleted_by: str
        """

        self._deleted_by = deleted_by
