# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, all_products: Link=None):  # noqa: E501
        """InlineResponse2005Links - a model defined in Swagger

        :param all_products: The all_products of this InlineResponse2005Links.  # noqa: E501
        :type all_products: Link
        """
        self.swagger_types = {
            'all_products': Link
        }

        self.attribute_map = {
            'all_products': 'all_products'
        }
        self._all_products = all_products

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5_links of this InlineResponse2005Links.  # noqa: E501
        :rtype: InlineResponse2005Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def all_products(self) -> Link:
        """Gets the all_products of this InlineResponse2005Links.


        :return: The all_products of this InlineResponse2005Links.
        :rtype: Link
        """
        return self._all_products

    @all_products.setter
    def all_products(self, all_products: Link):
        """Sets the all_products of this InlineResponse2005Links.


        :param all_products: The all_products of this InlineResponse2005Links.
        :type all_products: Link
        """

        self._all_products = all_products
