# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2004Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, updated_at: datetime=None, updated_by: str=None):  # noqa: E501
        """InlineResponse2004Meta - a model defined in Swagger

        :param updated_at: The updated_at of this InlineResponse2004Meta.  # noqa: E501
        :type updated_at: datetime
        :param updated_by: The updated_by of this InlineResponse2004Meta.  # noqa: E501
        :type updated_by: str
        """
        self.swagger_types = {
            'updated_at': datetime,
            'updated_by': str
        }

        self.attribute_map = {
            'updated_at': 'updated_at',
            'updated_by': 'updated_by'
        }
        self._updated_at = updated_at
        self._updated_by = updated_by

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4_meta of this InlineResponse2004Meta.  # noqa: E501
        :rtype: InlineResponse2004Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this InlineResponse2004Meta.


        :return: The updated_at of this InlineResponse2004Meta.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this InlineResponse2004Meta.


        :param updated_at: The updated_at of this InlineResponse2004Meta.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def updated_by(self) -> str:
        """Gets the updated_by of this InlineResponse2004Meta.


        :return: The updated_by of this InlineResponse2004Meta.
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by: str):
        """Sets the updated_by of this InlineResponse2004Meta.


        :param updated_by: The updated_by of this InlineResponse2004Meta.
        :type updated_by: str
        """

        self._updated_by = updated_by
