# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class InlineResponse201Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: Link=None, update: Link=None, delete: Link=None, all_products: Link=None):  # noqa: E501
        """InlineResponse201Links - a model defined in Swagger

        :param _self: The _self of this InlineResponse201Links.  # noqa: E501
        :type _self: Link
        :param update: The update of this InlineResponse201Links.  # noqa: E501
        :type update: Link
        :param delete: The delete of this InlineResponse201Links.  # noqa: E501
        :type delete: Link
        :param all_products: The all_products of this InlineResponse201Links.  # noqa: E501
        :type all_products: Link
        """
        self.swagger_types = {
            '_self': Link,
            'update': Link,
            'delete': Link,
            'all_products': Link
        }

        self.attribute_map = {
            '_self': 'self',
            'update': 'update',
            'delete': 'delete',
            'all_products': 'all_products'
        }
        self.__self = _self
        self._update = update
        self._delete = delete
        self._all_products = all_products

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_links of this InlineResponse201Links.  # noqa: E501
        :rtype: InlineResponse201Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> Link:
        """Gets the _self of this InlineResponse201Links.


        :return: The _self of this InlineResponse201Links.
        :rtype: Link
        """
        return self.__self

    @_self.setter
    def _self(self, _self: Link):
        """Sets the _self of this InlineResponse201Links.


        :param _self: The _self of this InlineResponse201Links.
        :type _self: Link
        """

        self.__self = _self

    @property
    def update(self) -> Link:
        """Gets the update of this InlineResponse201Links.


        :return: The update of this InlineResponse201Links.
        :rtype: Link
        """
        return self._update

    @update.setter
    def update(self, update: Link):
        """Sets the update of this InlineResponse201Links.


        :param update: The update of this InlineResponse201Links.
        :type update: Link
        """

        self._update = update

    @property
    def delete(self) -> Link:
        """Gets the delete of this InlineResponse201Links.


        :return: The delete of this InlineResponse201Links.
        :rtype: Link
        """
        return self._delete

    @delete.setter
    def delete(self, delete: Link):
        """Sets the delete of this InlineResponse201Links.


        :param delete: The delete of this InlineResponse201Links.
        :type delete: Link
        """

        self._delete = delete

    @property
    def all_products(self) -> Link:
        """Gets the all_products of this InlineResponse201Links.


        :return: The all_products of this InlineResponse201Links.
        :rtype: Link
        """
        return self._all_products

    @all_products.setter
    def all_products(self, all_products: Link):
        """Sets the all_products of this InlineResponse201Links.


        :param all_products: The all_products of this InlineResponse201Links.
        :type all_products: Link
        """

        self._all_products = all_products
