# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_data import InlineResponse200Data  # noqa: F401,E501
from swagger_server.models.inline_response200_links import InlineResponse200Links  # noqa: F401,E501
from swagger_server.models.inline_response200_meta import InlineResponse200Meta  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: InlineResponse200Data=None, links: InlineResponse200Links=None, meta: InlineResponse200Meta=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param status: The status of this InlineResponse200.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse200.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: InlineResponse200Data
        :param links: The links of this InlineResponse200.  # noqa: E501
        :type links: InlineResponse200Links
        :param meta: The meta of this InlineResponse200.  # noqa: E501
        :type meta: InlineResponse200Meta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': InlineResponse200Data,
            'links': InlineResponse200Links,
            'meta': InlineResponse200Meta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse200.


        :return: The status of this InlineResponse200.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse200.


        :param status: The status of this InlineResponse200.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse200.


        :return: The message of this InlineResponse200.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse200.


        :param message: The message of this InlineResponse200.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> InlineResponse200Data:
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: InlineResponse200Data
        """
        return self._data

    @data.setter
    def data(self, data: InlineResponse200Data):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: InlineResponse200Data
        """

        self._data = data

    @property
    def links(self) -> InlineResponse200Links:
        """Gets the links of this InlineResponse200.


        :return: The links of this InlineResponse200.
        :rtype: InlineResponse200Links
        """
        return self._links

    @links.setter
    def links(self, links: InlineResponse200Links):
        """Sets the links of this InlineResponse200.


        :param links: The links of this InlineResponse200.
        :type links: InlineResponse200Links
        """

        self._links = links

    @property
    def meta(self) -> InlineResponse200Meta:
        """Gets the meta of this InlineResponse200.


        :return: The meta of this InlineResponse200.
        :rtype: InlineResponse200Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: InlineResponse200Meta):
        """Sets the meta of this InlineResponse200.


        :param meta: The meta of this InlineResponse200.
        :type meta: InlineResponse200Meta
        """

        self._meta = meta
