# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2002_meta import InlineResponse2002Meta  # noqa: F401,E501
from swagger_server.models.user_info import UserInfo  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: UserInfo=None, links: object=None, meta: InlineResponse2002Meta=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param status: The status of this InlineResponse2002.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse2002.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse2002.  # noqa: E501
        :type data: UserInfo
        :param links: The links of this InlineResponse2002.  # noqa: E501
        :type links: object
        :param meta: The meta of this InlineResponse2002.  # noqa: E501
        :type meta: InlineResponse2002Meta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': UserInfo,
            'links': object,
            'meta': InlineResponse2002Meta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse2002.


        :return: The status of this InlineResponse2002.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse2002.


        :param status: The status of this InlineResponse2002.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2002.


        :return: The message of this InlineResponse2002.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2002.


        :param message: The message of this InlineResponse2002.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> UserInfo:
        """Gets the data of this InlineResponse2002.


        :return: The data of this InlineResponse2002.
        :rtype: UserInfo
        """
        return self._data

    @data.setter
    def data(self, data: UserInfo):
        """Sets the data of this InlineResponse2002.


        :param data: The data of this InlineResponse2002.
        :type data: UserInfo
        """

        self._data = data

    @property
    def links(self) -> object:
        """Gets the links of this InlineResponse2002.


        :return: The links of this InlineResponse2002.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links: object):
        """Sets the links of this InlineResponse2002.


        :param links: The links of this InlineResponse2002.
        :type links: object
        """

        self._links = links

    @property
    def meta(self) -> InlineResponse2002Meta:
        """Gets the meta of this InlineResponse2002.


        :return: The meta of this InlineResponse2002.
        :rtype: InlineResponse2002Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: InlineResponse2002Meta):
        """Sets the meta of this InlineResponse2002.


        :param meta: The meta of this InlineResponse2002.
        :type meta: InlineResponse2002Meta
        """

        self._meta = meta
