# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Link(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, href: str=None, method: str=None):  # noqa: E501
        """Link - a model defined in Swagger

        :param href: The href of this Link.  # noqa: E501
        :type href: str
        :param method: The method of this Link.  # noqa: E501
        :type method: str
        """
        self.swagger_types = {
            'href': str,
            'method': str
        }

        self.attribute_map = {
            'href': 'href',
            'method': 'method'
        }
        self._href = href
        self._method = method

    @classmethod
    def from_dict(cls, dikt) -> 'Link':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Link of this Link.  # noqa: E501
        :rtype: Link
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """Gets the href of this Link.


        :return: The href of this Link.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this Link.


        :param href: The href of this Link.
        :type href: str
        """

        self._href = href

    @property
    def method(self) -> str:
        """Gets the method of this Link.


        :return: The method of this Link.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this Link.


        :param method: The method of this Link.
        :type method: str
        """
        allowed_values = ["GET", "POST", "PUT", "DELETE", "PATCH"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"
                .format(method, allowed_values)
            )

        self._method = method
