# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class LoginResponseLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: Link=None, verify: Link=None, refresh: Link=None, logout: Link=None, products: Link=None, statistics: Link=None):  # noqa: E501
        """LoginResponseLinks - a model defined in Swagger

        :param _self: The _self of this LoginResponseLinks.  # noqa: E501
        :type _self: Link
        :param verify: The verify of this LoginResponseLinks.  # noqa: E501
        :type verify: Link
        :param refresh: The refresh of this LoginResponseLinks.  # noqa: E501
        :type refresh: Link
        :param logout: The logout of this LoginResponseLinks.  # noqa: E501
        :type logout: Link
        :param products: The products of this LoginResponseLinks.  # noqa: E501
        :type products: Link
        :param statistics: The statistics of this LoginResponseLinks.  # noqa: E501
        :type statistics: Link
        """
        self.swagger_types = {
            '_self': Link,
            'verify': Link,
            'refresh': Link,
            'logout': Link,
            'products': Link,
            'statistics': Link
        }

        self.attribute_map = {
            '_self': 'self',
            'verify': 'verify',
            'refresh': 'refresh',
            'logout': 'logout',
            'products': 'products',
            'statistics': 'statistics'
        }
        self.__self = _self
        self._verify = verify
        self._refresh = refresh
        self._logout = logout
        self._products = products
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponseLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse_links of this LoginResponseLinks.  # noqa: E501
        :rtype: LoginResponseLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> Link:
        """Gets the _self of this LoginResponseLinks.


        :return: The _self of this LoginResponseLinks.
        :rtype: Link
        """
        return self.__self

    @_self.setter
    def _self(self, _self: Link):
        """Sets the _self of this LoginResponseLinks.


        :param _self: The _self of this LoginResponseLinks.
        :type _self: Link
        """

        self.__self = _self

    @property
    def verify(self) -> Link:
        """Gets the verify of this LoginResponseLinks.


        :return: The verify of this LoginResponseLinks.
        :rtype: Link
        """
        return self._verify

    @verify.setter
    def verify(self, verify: Link):
        """Sets the verify of this LoginResponseLinks.


        :param verify: The verify of this LoginResponseLinks.
        :type verify: Link
        """

        self._verify = verify

    @property
    def refresh(self) -> Link:
        """Gets the refresh of this LoginResponseLinks.


        :return: The refresh of this LoginResponseLinks.
        :rtype: Link
        """
        return self._refresh

    @refresh.setter
    def refresh(self, refresh: Link):
        """Sets the refresh of this LoginResponseLinks.


        :param refresh: The refresh of this LoginResponseLinks.
        :type refresh: Link
        """

        self._refresh = refresh

    @property
    def logout(self) -> Link:
        """Gets the logout of this LoginResponseLinks.


        :return: The logout of this LoginResponseLinks.
        :rtype: Link
        """
        return self._logout

    @logout.setter
    def logout(self, logout: Link):
        """Sets the logout of this LoginResponseLinks.


        :param logout: The logout of this LoginResponseLinks.
        :type logout: Link
        """

        self._logout = logout

    @property
    def products(self) -> Link:
        """Gets the products of this LoginResponseLinks.


        :return: The products of this LoginResponseLinks.
        :rtype: Link
        """
        return self._products

    @products.setter
    def products(self, products: Link):
        """Sets the products of this LoginResponseLinks.


        :param products: The products of this LoginResponseLinks.
        :type products: Link
        """

        self._products = products

    @property
    def statistics(self) -> Link:
        """Gets the statistics of this LoginResponseLinks.


        :return: The statistics of this LoginResponseLinks.
        :rtype: Link
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: Link):
        """Sets the statistics of this LoginResponseLinks.


        :param statistics: The statistics of this LoginResponseLinks.
        :type statistics: Link
        """

        self._statistics = statistics
