# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, username: str=None, role: str=None, access_token: str=None, refresh_token: str=None):  # noqa: E501
        """LoginResponseData - a model defined in Swagger

        :param id: The id of this LoginResponseData.  # noqa: E501
        :type id: int
        :param username: The username of this LoginResponseData.  # noqa: E501
        :type username: str
        :param role: The role of this LoginResponseData.  # noqa: E501
        :type role: str
        :param access_token: The access_token of this LoginResponseData.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this LoginResponseData.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'role': str,
            'access_token': str,
            'refresh_token': str
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'role': 'role',
            'access_token': 'access_token',
            'refresh_token': 'refresh_token'
        }
        self._id = id
        self._username = username
        self._role = role
        self._access_token = access_token
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse_data of this LoginResponseData.  # noqa: E501
        :rtype: LoginResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this LoginResponseData.


        :return: The id of this LoginResponseData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this LoginResponseData.


        :param id: The id of this LoginResponseData.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this LoginResponseData.


        :return: The username of this LoginResponseData.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this LoginResponseData.


        :param username: The username of this LoginResponseData.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def role(self) -> str:
        """Gets the role of this LoginResponseData.


        :return: The role of this LoginResponseData.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this LoginResponseData.


        :param role: The role of this LoginResponseData.
        :type role: str
        """
        allowed_values = ["admin", "user"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def access_token(self) -> str:
        """Gets the access_token of this LoginResponseData.


        :return: The access_token of this LoginResponseData.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this LoginResponseData.


        :param access_token: The access_token of this LoginResponseData.
        :type access_token: str
        """
        if access_token is None:
            raise ValueError("Invalid value for `access_token`, must not be `None`")  # noqa: E501

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this LoginResponseData.


        :return: The refresh_token of this LoginResponseData.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this LoginResponseData.


        :param refresh_token: The refresh_token of this LoginResponseData.
        :type refresh_token: str
        """
        if refresh_token is None:
            raise ValueError("Invalid value for `refresh_token`, must not be `None`")  # noqa: E501

        self._refresh_token = refresh_token
