# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.login_response_data import LoginResponseData  # noqa: F401,E501
from swagger_server.models.login_response_links import LoginResponseLinks  # noqa: F401,E501
from swagger_server.models.login_response_meta import LoginResponseMeta  # noqa: F401,E501
from swagger_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: LoginResponseData=None, links: LoginResponseLinks=None, meta: LoginResponseMeta=None):  # noqa: E501
        """LoginResponse - a model defined in Swagger

        :param status: The status of this LoginResponse.  # noqa: E501
        :type status: str
        :param message: The message of this LoginResponse.  # noqa: E501
        :type message: str
        :param data: The data of this LoginResponse.  # noqa: E501
        :type data: LoginResponseData
        :param links: The links of this LoginResponse.  # noqa: E501
        :type links: LoginResponseLinks
        :param meta: The meta of this LoginResponse.  # noqa: E501
        :type meta: LoginResponseMeta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': LoginResponseData,
            'links': LoginResponseLinks,
            'meta': LoginResponseMeta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this LoginResponse.


        :return: The status of this LoginResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this LoginResponse.


        :param status: The status of this LoginResponse.
        :type status: str
        """
        allowed_values = ["success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this LoginResponse.


        :return: The message of this LoginResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this LoginResponse.


        :param message: The message of this LoginResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> LoginResponseData:
        """Gets the data of this LoginResponse.


        :return: The data of this LoginResponse.
        :rtype: LoginResponseData
        """
        return self._data

    @data.setter
    def data(self, data: LoginResponseData):
        """Sets the data of this LoginResponse.


        :param data: The data of this LoginResponse.
        :type data: LoginResponseData
        """

        self._data = data

    @property
    def links(self) -> LoginResponseLinks:
        """Gets the links of this LoginResponse.


        :return: The links of this LoginResponse.
        :rtype: LoginResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links: LoginResponseLinks):
        """Sets the links of this LoginResponse.


        :param links: The links of this LoginResponse.
        :type links: LoginResponseLinks
        """

        self._links = links

    @property
    def meta(self) -> LoginResponseMeta:
        """Gets the meta of this LoginResponse.


        :return: The meta of this LoginResponse.
        :rtype: LoginResponseMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: LoginResponseMeta):
        """Sets the meta of this LoginResponse.


        :param meta: The meta of this LoginResponse.
        :type meta: LoginResponseMeta
        """

        self._meta = meta
