# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginResponseMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token_expires_in: int=None, refresh_token_expires_in: int=None, timestamp: datetime=None):  # noqa: E501
        """LoginResponseMeta - a model defined in Swagger

        :param access_token_expires_in: The access_token_expires_in of this LoginResponseMeta.  # noqa: E501
        :type access_token_expires_in: int
        :param refresh_token_expires_in: The refresh_token_expires_in of this LoginResponseMeta.  # noqa: E501
        :type refresh_token_expires_in: int
        :param timestamp: The timestamp of this LoginResponseMeta.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'access_token_expires_in': int,
            'refresh_token_expires_in': int,
            'timestamp': datetime
        }

        self.attribute_map = {
            'access_token_expires_in': 'access_token_expires_in',
            'refresh_token_expires_in': 'refresh_token_expires_in',
            'timestamp': 'timestamp'
        }
        self._access_token_expires_in = access_token_expires_in
        self._refresh_token_expires_in = refresh_token_expires_in
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponseMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse_meta of this LoginResponseMeta.  # noqa: E501
        :rtype: LoginResponseMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token_expires_in(self) -> int:
        """Gets the access_token_expires_in of this LoginResponseMeta.

        Access token lifetime in seconds  # noqa: E501

        :return: The access_token_expires_in of this LoginResponseMeta.
        :rtype: int
        """
        return self._access_token_expires_in

    @access_token_expires_in.setter
    def access_token_expires_in(self, access_token_expires_in: int):
        """Sets the access_token_expires_in of this LoginResponseMeta.

        Access token lifetime in seconds  # noqa: E501

        :param access_token_expires_in: The access_token_expires_in of this LoginResponseMeta.
        :type access_token_expires_in: int
        """

        self._access_token_expires_in = access_token_expires_in

    @property
    def refresh_token_expires_in(self) -> int:
        """Gets the refresh_token_expires_in of this LoginResponseMeta.

        Refresh token lifetime in seconds  # noqa: E501

        :return: The refresh_token_expires_in of this LoginResponseMeta.
        :rtype: int
        """
        return self._refresh_token_expires_in

    @refresh_token_expires_in.setter
    def refresh_token_expires_in(self, refresh_token_expires_in: int):
        """Sets the refresh_token_expires_in of this LoginResponseMeta.

        Refresh token lifetime in seconds  # noqa: E501

        :param refresh_token_expires_in: The refresh_token_expires_in of this LoginResponseMeta.
        :type refresh_token_expires_in: int
        """

        self._refresh_token_expires_in = refresh_token_expires_in

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this LoginResponseMeta.


        :return: The timestamp of this LoginResponseMeta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this LoginResponseMeta.


        :param timestamp: The timestamp of this LoginResponseMeta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
