# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogoutRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, refresh_token: str=None):  # noqa: E501
        """LogoutRequest - a model defined in Swagger

        :param refresh_token: The refresh_token of this LogoutRequest.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'refresh_token': str
        }

        self.attribute_map = {
            'refresh_token': 'refresh_token'
        }
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'LogoutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogoutRequest of this LogoutRequest.  # noqa: E501
        :rtype: LogoutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this LogoutRequest.

        Optional refresh token to revoke  # noqa: E501

        :return: The refresh_token of this LogoutRequest.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this LogoutRequest.

        Optional refresh token to revoke  # noqa: E501

        :param refresh_token: The refresh_token of this LogoutRequest.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
