# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class ProductsListResponseLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: Link=None, create: Link=None, prev: Link=None, next: Link=None, first: Link=None, last: Link=None):  # noqa: E501
        """ProductsListResponseLinks - a model defined in Swagger

        :param _self: The _self of this ProductsListResponseLinks.  # noqa: E501
        :type _self: Link
        :param create: The create of this ProductsListResponseLinks.  # noqa: E501
        :type create: Link
        :param prev: The prev of this ProductsListResponseLinks.  # noqa: E501
        :type prev: Link
        :param next: The next of this ProductsListResponseLinks.  # noqa: E501
        :type next: Link
        :param first: The first of this ProductsListResponseLinks.  # noqa: E501
        :type first: Link
        :param last: The last of this ProductsListResponseLinks.  # noqa: E501
        :type last: Link
        """
        self.swagger_types = {
            '_self': Link,
            'create': Link,
            'prev': Link,
            'next': Link,
            'first': Link,
            'last': Link
        }

        self.attribute_map = {
            '_self': 'self',
            'create': 'create',
            'prev': 'prev',
            'next': 'next',
            'first': 'first',
            'last': 'last'
        }
        self.__self = _self
        self._create = create
        self._prev = prev
        self._next = next
        self._first = first
        self._last = last

    @classmethod
    def from_dict(cls, dikt) -> 'ProductsListResponseLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductsListResponse_links of this ProductsListResponseLinks.  # noqa: E501
        :rtype: ProductsListResponseLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> Link:
        """Gets the _self of this ProductsListResponseLinks.


        :return: The _self of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self.__self

    @_self.setter
    def _self(self, _self: Link):
        """Sets the _self of this ProductsListResponseLinks.


        :param _self: The _self of this ProductsListResponseLinks.
        :type _self: Link
        """

        self.__self = _self

    @property
    def create(self) -> Link:
        """Gets the create of this ProductsListResponseLinks.


        :return: The create of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self._create

    @create.setter
    def create(self, create: Link):
        """Sets the create of this ProductsListResponseLinks.


        :param create: The create of this ProductsListResponseLinks.
        :type create: Link
        """

        self._create = create

    @property
    def prev(self) -> Link:
        """Gets the prev of this ProductsListResponseLinks.


        :return: The prev of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self._prev

    @prev.setter
    def prev(self, prev: Link):
        """Sets the prev of this ProductsListResponseLinks.


        :param prev: The prev of this ProductsListResponseLinks.
        :type prev: Link
        """

        self._prev = prev

    @property
    def next(self) -> Link:
        """Gets the next of this ProductsListResponseLinks.


        :return: The next of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self._next

    @next.setter
    def next(self, next: Link):
        """Sets the next of this ProductsListResponseLinks.


        :param next: The next of this ProductsListResponseLinks.
        :type next: Link
        """

        self._next = next

    @property
    def first(self) -> Link:
        """Gets the first of this ProductsListResponseLinks.


        :return: The first of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self._first

    @first.setter
    def first(self, first: Link):
        """Sets the first of this ProductsListResponseLinks.


        :param first: The first of this ProductsListResponseLinks.
        :type first: Link
        """

        self._first = first

    @property
    def last(self) -> Link:
        """Gets the last of this ProductsListResponseLinks.


        :return: The last of this ProductsListResponseLinks.
        :rtype: Link
        """
        return self._last

    @last.setter
    def last(self, last: Link):
        """Sets the last of this ProductsListResponseLinks.


        :param last: The last of this ProductsListResponseLinks.
        :type last: Link
        """

        self._last = last
