# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductsListResponseMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_count: int=None, page: int=None, limit: int=None, total_pages: int=None, timestamp: datetime=None):  # noqa: E501
        """ProductsListResponseMeta - a model defined in Swagger

        :param total_count: The total_count of this ProductsListResponseMeta.  # noqa: E501
        :type total_count: int
        :param page: The page of this ProductsListResponseMeta.  # noqa: E501
        :type page: int
        :param limit: The limit of this ProductsListResponseMeta.  # noqa: E501
        :type limit: int
        :param total_pages: The total_pages of this ProductsListResponseMeta.  # noqa: E501
        :type total_pages: int
        :param timestamp: The timestamp of this ProductsListResponseMeta.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'total_count': int,
            'page': int,
            'limit': int,
            'total_pages': int,
            'timestamp': datetime
        }

        self.attribute_map = {
            'total_count': 'total_count',
            'page': 'page',
            'limit': 'limit',
            'total_pages': 'total_pages',
            'timestamp': 'timestamp'
        }
        self._total_count = total_count
        self._page = page
        self._limit = limit
        self._total_pages = total_pages
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'ProductsListResponseMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductsListResponse_meta of this ProductsListResponseMeta.  # noqa: E501
        :rtype: ProductsListResponseMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_count(self) -> int:
        """Gets the total_count of this ProductsListResponseMeta.

        Total number of products  # noqa: E501

        :return: The total_count of this ProductsListResponseMeta.
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count: int):
        """Sets the total_count of this ProductsListResponseMeta.

        Total number of products  # noqa: E501

        :param total_count: The total_count of this ProductsListResponseMeta.
        :type total_count: int
        """

        self._total_count = total_count

    @property
    def page(self) -> int:
        """Gets the page of this ProductsListResponseMeta.

        Current page number  # noqa: E501

        :return: The page of this ProductsListResponseMeta.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this ProductsListResponseMeta.

        Current page number  # noqa: E501

        :param page: The page of this ProductsListResponseMeta.
        :type page: int
        """

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this ProductsListResponseMeta.

        Items per page  # noqa: E501

        :return: The limit of this ProductsListResponseMeta.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this ProductsListResponseMeta.

        Items per page  # noqa: E501

        :param limit: The limit of this ProductsListResponseMeta.
        :type limit: int
        """

        self._limit = limit

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this ProductsListResponseMeta.

        Total number of pages  # noqa: E501

        :return: The total_pages of this ProductsListResponseMeta.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this ProductsListResponseMeta.

        Total number of pages  # noqa: E501

        :param total_pages: The total_pages of this ProductsListResponseMeta.
        :type total_pages: int
        """

        self._total_pages = total_pages

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this ProductsListResponseMeta.


        :return: The timestamp of this ProductsListResponseMeta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this ProductsListResponseMeta.


        :param timestamp: The timestamp of this ProductsListResponseMeta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
