# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server.models.products_list_response_links import ProductsListResponseLinks  # noqa: F401,E501
from swagger_server.models.products_list_response_meta import ProductsListResponseMeta  # noqa: F401,E501
from swagger_server import util


class ProductsListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: List[Product]=None, links: ProductsListResponseLinks=None, meta: ProductsListResponseMeta=None):  # noqa: E501
        """ProductsListResponse - a model defined in Swagger

        :param status: The status of this ProductsListResponse.  # noqa: E501
        :type status: str
        :param message: The message of this ProductsListResponse.  # noqa: E501
        :type message: str
        :param data: The data of this ProductsListResponse.  # noqa: E501
        :type data: List[Product]
        :param links: The links of this ProductsListResponse.  # noqa: E501
        :type links: ProductsListResponseLinks
        :param meta: The meta of this ProductsListResponse.  # noqa: E501
        :type meta: ProductsListResponseMeta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': List[Product],
            'links': ProductsListResponseLinks,
            'meta': ProductsListResponseMeta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'ProductsListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductsListResponse of this ProductsListResponse.  # noqa: E501
        :rtype: ProductsListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this ProductsListResponse.


        :return: The status of this ProductsListResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ProductsListResponse.


        :param status: The status of this ProductsListResponse.
        :type status: str
        """
        allowed_values = ["success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this ProductsListResponse.


        :return: The message of this ProductsListResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ProductsListResponse.


        :param message: The message of this ProductsListResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[Product]:
        """Gets the data of this ProductsListResponse.


        :return: The data of this ProductsListResponse.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this ProductsListResponse.


        :param data: The data of this ProductsListResponse.
        :type data: List[Product]
        """

        self._data = data

    @property
    def links(self) -> ProductsListResponseLinks:
        """Gets the links of this ProductsListResponse.


        :return: The links of this ProductsListResponse.
        :rtype: ProductsListResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links: ProductsListResponseLinks):
        """Sets the links of this ProductsListResponse.


        :param links: The links of this ProductsListResponse.
        :type links: ProductsListResponseLinks
        """

        self._links = links

    @property
    def meta(self) -> ProductsListResponseMeta:
        """Gets the meta of this ProductsListResponse.


        :return: The meta of this ProductsListResponse.
        :rtype: ProductsListResponseMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: ProductsListResponseMeta):
        """Sets the meta of this ProductsListResponse.


        :param meta: The meta of this ProductsListResponse.
        :type meta: ProductsListResponseMeta
        """

        self._meta = meta
