# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, sku: str=None, name: str=None, description: str=None, category: str=None, brand: str=None, price: float=None, currency: str='USD', quantity: int=None, image_url: str=None, status: str=None, created_at: datetime=None, updated_at: datetime=None, links: Dict[str, Link]=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param id: The id of this Product.  # noqa: E501
    :type id: str
        :param sku: The sku of this Product.  # noqa: E501
        :type sku: str
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param description: The description of this Product.  # noqa: E501
        :type description: str
        :param category: The category of this Product.  # noqa: E501
        :type category: str
        :param brand: The brand of this Product.  # noqa: E501
        :type brand: str
        :param price: The price of this Product.  # noqa: E501
        :type price: float
        :param currency: The currency of this Product.  # noqa: E501
        :type currency: str
        :param quantity: The quantity of this Product.  # noqa: E501
        :type quantity: int
        :param image_url: The image_url of this Product.  # noqa: E501
        :type image_url: str
        :param status: The status of this Product.  # noqa: E501
        :type status: str
        :param created_at: The created_at of this Product.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Product.  # noqa: E501
        :type updated_at: datetime
        :param links: The links of this Product.  # noqa: E501
        :type links: Dict[str, Link]
        """
        self.swagger_types = {
            'id': str,
            'sku': str,
            'name': str,
            'description': str,
            'category': str,
            'brand': str,
            'price': float,
            'currency': str,
            'quantity': int,
            'image_url': str,
            'status': str,
            'created_at': datetime,
            'updated_at': datetime,
            'links': Dict[str, Link]
        }

        self.attribute_map = {
            'id': 'id',
            'sku': 'sku',
            'name': 'name',
            'description': 'description',
            'category': 'category',
            'brand': 'brand',
            'price': 'price',
            'currency': 'currency',
            'quantity': 'quantity',
            'image_url': 'image_url',
            'status': 'status',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'links': 'links'
        }
        self._id = id
        self._sku = sku
        self._name = name
        self._description = description
        self._category = category
        self._brand = brand
        self._price = price
        self._currency = currency
        self._quantity = quantity
        self._image_url = image_url
        self._status = status
        self._created_at = created_at
        self._updated_at = updated_at
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Product.

        Unique product identifier  # noqa: E501

        :return: The id of this Product.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Product.

        Unique product identifier  # noqa: E501

        :param id: The id of this Product.
    :type id: str
        """

        self._id = id

    @property
    def sku(self) -> str:
        """Gets the sku of this Product.

        Stock Keeping Unit - unique product code  # noqa: E501

        :return: The sku of this Product.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this Product.

        Stock Keeping Unit - unique product code  # noqa: E501

        :param sku: The sku of this Product.
        :type sku: str
        """

        self._sku = sku

    @property
    def name(self) -> str:
        """Gets the name of this Product.

        Product name  # noqa: E501

        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.

        Product name  # noqa: E501

        :param name: The name of this Product.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Product.

        Product description  # noqa: E501

        :return: The description of this Product.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Product.

        Product description  # noqa: E501

        :param description: The description of this Product.
        :type description: str
        """

        self._description = description

    @property
    def category(self) -> str:
        """Gets the category of this Product.

        Product category  # noqa: E501

        :return: The category of this Product.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Product.

        Product category  # noqa: E501

        :param category: The category of this Product.
        :type category: str
        """

        self._category = category

    @property
    def brand(self) -> str:
        """Gets the brand of this Product.

        Product brand/manufacturer  # noqa: E501

        :return: The brand of this Product.
        :rtype: str
        """
        return self._brand

    @brand.setter
    def brand(self, brand: str):
        """Sets the brand of this Product.

        Product brand/manufacturer  # noqa: E501

        :param brand: The brand of this Product.
        :type brand: str
        """

        self._brand = brand

    @property
    def price(self) -> float:
        """Gets the price of this Product.

        Product price in USD  # noqa: E501

        :return: The price of this Product.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Product.

        Product price in USD  # noqa: E501

        :param price: The price of this Product.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this Product.

        Currency code  # noqa: E501

        :return: The currency of this Product.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this Product.

        Currency code  # noqa: E501

        :param currency: The currency of this Product.
        :type currency: str
        """

        self._currency = currency

    @property
    def quantity(self) -> int:
        """Gets the quantity of this Product.

        Available quantity in stock  # noqa: E501

        :return: The quantity of this Product.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this Product.

        Available quantity in stock  # noqa: E501

        :param quantity: The quantity of this Product.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def image_url(self) -> str:
        """Gets the image_url of this Product.

        Product image URL  # noqa: E501

        :return: The image_url of this Product.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this Product.

        Product image URL  # noqa: E501

        :param image_url: The image_url of this Product.
        :type image_url: str
        """

        self._image_url = image_url

    @property
    def status(self) -> str:
        """Gets the status of this Product.

        Product status  # noqa: E501

        :return: The status of this Product.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Product.

        Product status  # noqa: E501

        :param status: The status of this Product.
        :type status: str
        """
        allowed_values = ["active", "inactive", "discontinued"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Product.

        Product creation timestamp  # noqa: E501

        :return: The created_at of this Product.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Product.

        Product creation timestamp  # noqa: E501

        :param created_at: The created_at of this Product.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Product.

        Last update timestamp  # noqa: E501

        :return: The updated_at of this Product.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Product.

        Last update timestamp  # noqa: E501

        :param updated_at: The updated_at of this Product.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def links(self) -> Dict[str, Link]:
        """Gets the links of this Product.

        HATEOAS links for related actions  # noqa: E501

        :return: The links of this Product.
        :rtype: Dict[str, Link]
        """
        return self._links

    @links.setter
    def links(self, links: Dict[str, Link]):
        """Sets the links of this Product.

        HATEOAS links for related actions  # noqa: E501

        :param links: The links of this Product.
        :type links: Dict[str, Link]
        """

        self._links = links
