# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RefreshResponseMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token_expires_in: int=None, timestamp: datetime=None):  # noqa: E501
        """RefreshResponseMeta - a model defined in Swagger

        :param access_token_expires_in: The access_token_expires_in of this RefreshResponseMeta.  # noqa: E501
        :type access_token_expires_in: int
        :param timestamp: The timestamp of this RefreshResponseMeta.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'access_token_expires_in': int,
            'timestamp': datetime
        }

        self.attribute_map = {
            'access_token_expires_in': 'access_token_expires_in',
            'timestamp': 'timestamp'
        }
        self._access_token_expires_in = access_token_expires_in
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'RefreshResponseMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RefreshResponse_meta of this RefreshResponseMeta.  # noqa: E501
        :rtype: RefreshResponseMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token_expires_in(self) -> int:
        """Gets the access_token_expires_in of this RefreshResponseMeta.


        :return: The access_token_expires_in of this RefreshResponseMeta.
        :rtype: int
        """
        return self._access_token_expires_in

    @access_token_expires_in.setter
    def access_token_expires_in(self, access_token_expires_in: int):
        """Sets the access_token_expires_in of this RefreshResponseMeta.


        :param access_token_expires_in: The access_token_expires_in of this RefreshResponseMeta.
        :type access_token_expires_in: int
        """

        self._access_token_expires_in = access_token_expires_in

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this RefreshResponseMeta.


        :return: The timestamp of this RefreshResponseMeta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this RefreshResponseMeta.


        :param timestamp: The timestamp of this RefreshResponseMeta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
