# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.refresh_response_data import RefreshResponseData  # noqa: F401,E501
from swagger_server.models.refresh_response_meta import RefreshResponseMeta  # noqa: F401,E501
from swagger_server import util


class RefreshResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, data: RefreshResponseData=None, links: object=None, meta: RefreshResponseMeta=None):  # noqa: E501
        """RefreshResponse - a model defined in Swagger

        :param status: The status of this RefreshResponse.  # noqa: E501
        :type status: str
        :param message: The message of this RefreshResponse.  # noqa: E501
        :type message: str
        :param data: The data of this RefreshResponse.  # noqa: E501
        :type data: RefreshResponseData
        :param links: The links of this RefreshResponse.  # noqa: E501
        :type links: object
        :param meta: The meta of this RefreshResponse.  # noqa: E501
        :type meta: RefreshResponseMeta
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'data': RefreshResponseData,
            'links': object,
            'meta': RefreshResponseMeta
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'data': 'data',
            'links': 'links',
            'meta': 'meta'
        }
        self._status = status
        self._message = message
        self._data = data
        self._links = links
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'RefreshResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RefreshResponse of this RefreshResponse.  # noqa: E501
        :rtype: RefreshResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this RefreshResponse.


        :return: The status of this RefreshResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this RefreshResponse.


        :param status: The status of this RefreshResponse.
        :type status: str
        """
        allowed_values = ["success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this RefreshResponse.


        :return: The message of this RefreshResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this RefreshResponse.


        :param message: The message of this RefreshResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> RefreshResponseData:
        """Gets the data of this RefreshResponse.


        :return: The data of this RefreshResponse.
        :rtype: RefreshResponseData
        """
        return self._data

    @data.setter
    def data(self, data: RefreshResponseData):
        """Sets the data of this RefreshResponse.


        :param data: The data of this RefreshResponse.
        :type data: RefreshResponseData
        """

        self._data = data

    @property
    def links(self) -> object:
        """Gets the links of this RefreshResponse.


        :return: The links of this RefreshResponse.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links: object):
        """Sets the links of this RefreshResponse.


        :param links: The links of this RefreshResponse.
        :type links: object
        """

        self._links = links

    @property
    def meta(self) -> RefreshResponseMeta:
        """Gets the meta of this RefreshResponse.


        :return: The meta of this RefreshResponse.
        :rtype: RefreshResponseMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: RefreshResponseMeta):
        """Sets the meta of this RefreshResponse.


        :param meta: The meta of this RefreshResponse.
        :type meta: RefreshResponseMeta
        """

        self._meta = meta
