# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.statistics_data_categories import StatisticsDataCategories  # noqa: F401,E501
from swagger_server.models.statistics_data_inventory import StatisticsDataInventory  # noqa: F401,E501
from swagger_server.models.statistics_data_top_products import StatisticsDataTopProducts  # noqa: F401,E501
from swagger_server import util


class StatisticsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inventory: StatisticsDataInventory=None, categories: StatisticsDataCategories=None, top_products: List[StatisticsDataTopProducts]=None):  # noqa: E501
        """StatisticsData - a model defined in Swagger

        :param inventory: The inventory of this StatisticsData.  # noqa: E501
        :type inventory: StatisticsDataInventory
        :param categories: The categories of this StatisticsData.  # noqa: E501
        :type categories: StatisticsDataCategories
        :param top_products: The top_products of this StatisticsData.  # noqa: E501
        :type top_products: List[StatisticsDataTopProducts]
        """
        self.swagger_types = {
            'inventory': StatisticsDataInventory,
            'categories': StatisticsDataCategories,
            'top_products': List[StatisticsDataTopProducts]
        }

        self.attribute_map = {
            'inventory': 'inventory',
            'categories': 'categories',
            'top_products': 'top_products'
        }
        self._inventory = inventory
        self._categories = categories
        self._top_products = top_products

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_data of this StatisticsData.  # noqa: E501
        :rtype: StatisticsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inventory(self) -> StatisticsDataInventory:
        """Gets the inventory of this StatisticsData.


        :return: The inventory of this StatisticsData.
        :rtype: StatisticsDataInventory
        """
        return self._inventory

    @inventory.setter
    def inventory(self, inventory: StatisticsDataInventory):
        """Sets the inventory of this StatisticsData.


        :param inventory: The inventory of this StatisticsData.
        :type inventory: StatisticsDataInventory
        """

        self._inventory = inventory

    @property
    def categories(self) -> StatisticsDataCategories:
        """Gets the categories of this StatisticsData.


        :return: The categories of this StatisticsData.
        :rtype: StatisticsDataCategories
        """
        return self._categories

    @categories.setter
    def categories(self, categories: StatisticsDataCategories):
        """Sets the categories of this StatisticsData.


        :param categories: The categories of this StatisticsData.
        :type categories: StatisticsDataCategories
        """

        self._categories = categories

    @property
    def top_products(self) -> List[StatisticsDataTopProducts]:
        """Gets the top_products of this StatisticsData.

        Top 10 highest value products  # noqa: E501

        :return: The top_products of this StatisticsData.
        :rtype: List[StatisticsDataTopProducts]
        """
        return self._top_products

    @top_products.setter
    def top_products(self, top_products: List[StatisticsDataTopProducts]):
        """Sets the top_products of this StatisticsData.

        Top 10 highest value products  # noqa: E501

        :param top_products: The top_products of this StatisticsData.
        :type top_products: List[StatisticsDataTopProducts]
        """

        self._top_products = top_products
