# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.statistics_data_categories_category_breakdown import StatisticsDataCategoriesCategoryBreakdown  # noqa: F401,E501
from swagger_server import util


class StatisticsDataCategories(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_categories: int=None, category_breakdown: List[StatisticsDataCategoriesCategoryBreakdown]=None):  # noqa: E501
        """StatisticsDataCategories - a model defined in Swagger

        :param total_categories: The total_categories of this StatisticsDataCategories.  # noqa: E501
        :type total_categories: int
        :param category_breakdown: The category_breakdown of this StatisticsDataCategories.  # noqa: E501
        :type category_breakdown: List[StatisticsDataCategoriesCategoryBreakdown]
        """
        self.swagger_types = {
            'total_categories': int,
            'category_breakdown': List[StatisticsDataCategoriesCategoryBreakdown]
        }

        self.attribute_map = {
            'total_categories': 'total_categories',
            'category_breakdown': 'category_breakdown'
        }
        self._total_categories = total_categories
        self._category_breakdown = category_breakdown

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsDataCategories':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_data_categories of this StatisticsDataCategories.  # noqa: E501
        :rtype: StatisticsDataCategories
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_categories(self) -> int:
        """Gets the total_categories of this StatisticsDataCategories.

        Number of unique categories  # noqa: E501

        :return: The total_categories of this StatisticsDataCategories.
        :rtype: int
        """
        return self._total_categories

    @total_categories.setter
    def total_categories(self, total_categories: int):
        """Sets the total_categories of this StatisticsDataCategories.

        Number of unique categories  # noqa: E501

        :param total_categories: The total_categories of this StatisticsDataCategories.
        :type total_categories: int
        """

        self._total_categories = total_categories

    @property
    def category_breakdown(self) -> List[StatisticsDataCategoriesCategoryBreakdown]:
        """Gets the category_breakdown of this StatisticsDataCategories.


        :return: The category_breakdown of this StatisticsDataCategories.
        :rtype: List[StatisticsDataCategoriesCategoryBreakdown]
        """
        return self._category_breakdown

    @category_breakdown.setter
    def category_breakdown(self, category_breakdown: List[StatisticsDataCategoriesCategoryBreakdown]):
        """Sets the category_breakdown of this StatisticsDataCategories.


        :param category_breakdown: The category_breakdown of this StatisticsDataCategories.
        :type category_breakdown: List[StatisticsDataCategoriesCategoryBreakdown]
        """

        self._category_breakdown = category_breakdown
