# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatisticsDataInventory(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_products: int=None, total_quantity: int=None, total_value: float=None, active_products: int=None, inactive_products: int=None, discontinued_products: int=None, out_of_stock: int=None, low_stock: int=None):  # noqa: E501
        """StatisticsDataInventory - a model defined in Swagger

        :param total_products: The total_products of this StatisticsDataInventory.  # noqa: E501
        :type total_products: int
        :param total_quantity: The total_quantity of this StatisticsDataInventory.  # noqa: E501
        :type total_quantity: int
        :param total_value: The total_value of this StatisticsDataInventory.  # noqa: E501
        :type total_value: float
        :param active_products: The active_products of this StatisticsDataInventory.  # noqa: E501
        :type active_products: int
        :param inactive_products: The inactive_products of this StatisticsDataInventory.  # noqa: E501
        :type inactive_products: int
        :param discontinued_products: The discontinued_products of this StatisticsDataInventory.  # noqa: E501
        :type discontinued_products: int
        :param out_of_stock: The out_of_stock of this StatisticsDataInventory.  # noqa: E501
        :type out_of_stock: int
        :param low_stock: The low_stock of this StatisticsDataInventory.  # noqa: E501
        :type low_stock: int
        """
        self.swagger_types = {
            'total_products': int,
            'total_quantity': int,
            'total_value': float,
            'active_products': int,
            'inactive_products': int,
            'discontinued_products': int,
            'out_of_stock': int,
            'low_stock': int
        }

        self.attribute_map = {
            'total_products': 'total_products',
            'total_quantity': 'total_quantity',
            'total_value': 'total_value',
            'active_products': 'active_products',
            'inactive_products': 'inactive_products',
            'discontinued_products': 'discontinued_products',
            'out_of_stock': 'out_of_stock',
            'low_stock': 'low_stock'
        }
        self._total_products = total_products
        self._total_quantity = total_quantity
        self._total_value = total_value
        self._active_products = active_products
        self._inactive_products = inactive_products
        self._discontinued_products = discontinued_products
        self._out_of_stock = out_of_stock
        self._low_stock = low_stock

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsDataInventory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_data_inventory of this StatisticsDataInventory.  # noqa: E501
        :rtype: StatisticsDataInventory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_products(self) -> int:
        """Gets the total_products of this StatisticsDataInventory.

        Total number of unique products  # noqa: E501

        :return: The total_products of this StatisticsDataInventory.
        :rtype: int
        """
        return self._total_products

    @total_products.setter
    def total_products(self, total_products: int):
        """Sets the total_products of this StatisticsDataInventory.

        Total number of unique products  # noqa: E501

        :param total_products: The total_products of this StatisticsDataInventory.
        :type total_products: int
        """

        self._total_products = total_products

    @property
    def total_quantity(self) -> int:
        """Gets the total_quantity of this StatisticsDataInventory.

        Total quantity across all products  # noqa: E501

        :return: The total_quantity of this StatisticsDataInventory.
        :rtype: int
        """
        return self._total_quantity

    @total_quantity.setter
    def total_quantity(self, total_quantity: int):
        """Sets the total_quantity of this StatisticsDataInventory.

        Total quantity across all products  # noqa: E501

        :param total_quantity: The total_quantity of this StatisticsDataInventory.
        :type total_quantity: int
        """

        self._total_quantity = total_quantity

    @property
    def total_value(self) -> float:
        """Gets the total_value of this StatisticsDataInventory.

        Total inventory value  # noqa: E501

        :return: The total_value of this StatisticsDataInventory.
        :rtype: float
        """
        return self._total_value

    @total_value.setter
    def total_value(self, total_value: float):
        """Sets the total_value of this StatisticsDataInventory.

        Total inventory value  # noqa: E501

        :param total_value: The total_value of this StatisticsDataInventory.
        :type total_value: float
        """

        self._total_value = total_value

    @property
    def active_products(self) -> int:
        """Gets the active_products of this StatisticsDataInventory.

        Number of active products  # noqa: E501

        :return: The active_products of this StatisticsDataInventory.
        :rtype: int
        """
        return self._active_products

    @active_products.setter
    def active_products(self, active_products: int):
        """Sets the active_products of this StatisticsDataInventory.

        Number of active products  # noqa: E501

        :param active_products: The active_products of this StatisticsDataInventory.
        :type active_products: int
        """

        self._active_products = active_products

    @property
    def inactive_products(self) -> int:
        """Gets the inactive_products of this StatisticsDataInventory.

        Number of inactive products  # noqa: E501

        :return: The inactive_products of this StatisticsDataInventory.
        :rtype: int
        """
        return self._inactive_products

    @inactive_products.setter
    def inactive_products(self, inactive_products: int):
        """Sets the inactive_products of this StatisticsDataInventory.

        Number of inactive products  # noqa: E501

        :param inactive_products: The inactive_products of this StatisticsDataInventory.
        :type inactive_products: int
        """

        self._inactive_products = inactive_products

    @property
    def discontinued_products(self) -> int:
        """Gets the discontinued_products of this StatisticsDataInventory.

        Number of discontinued products  # noqa: E501

        :return: The discontinued_products of this StatisticsDataInventory.
        :rtype: int
        """
        return self._discontinued_products

    @discontinued_products.setter
    def discontinued_products(self, discontinued_products: int):
        """Sets the discontinued_products of this StatisticsDataInventory.

        Number of discontinued products  # noqa: E501

        :param discontinued_products: The discontinued_products of this StatisticsDataInventory.
        :type discontinued_products: int
        """

        self._discontinued_products = discontinued_products

    @property
    def out_of_stock(self) -> int:
        """Gets the out_of_stock of this StatisticsDataInventory.

        Number of out-of-stock products  # noqa: E501

        :return: The out_of_stock of this StatisticsDataInventory.
        :rtype: int
        """
        return self._out_of_stock

    @out_of_stock.setter
    def out_of_stock(self, out_of_stock: int):
        """Sets the out_of_stock of this StatisticsDataInventory.

        Number of out-of-stock products  # noqa: E501

        :param out_of_stock: The out_of_stock of this StatisticsDataInventory.
        :type out_of_stock: int
        """

        self._out_of_stock = out_of_stock

    @property
    def low_stock(self) -> int:
        """Gets the low_stock of this StatisticsDataInventory.

        Number of products with low stock (< 10 units)  # noqa: E501

        :return: The low_stock of this StatisticsDataInventory.
        :rtype: int
        """
        return self._low_stock

    @low_stock.setter
    def low_stock(self, low_stock: int):
        """Sets the low_stock of this StatisticsDataInventory.

        Number of products with low stock (< 10 units)  # noqa: E501

        :param low_stock: The low_stock of this StatisticsDataInventory.
        :type low_stock: int
        """

        self._low_stock = low_stock
