# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatisticsMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, requested_by: str=None):  # noqa: E501
        """StatisticsMeta - a model defined in Swagger

        :param timestamp: The timestamp of this StatisticsMeta.  # noqa: E501
        :type timestamp: datetime
        :param requested_by: The requested_by of this StatisticsMeta.  # noqa: E501
        :type requested_by: str
        """
        self.swagger_types = {
            'timestamp': datetime,
            'requested_by': str
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'requested_by': 'requested_by'
        }
        self._timestamp = timestamp
        self._requested_by = requested_by

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_meta of this StatisticsMeta.  # noqa: E501
        :rtype: StatisticsMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this StatisticsMeta.


        :return: The timestamp of this StatisticsMeta.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this StatisticsMeta.


        :param timestamp: The timestamp of this StatisticsMeta.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def requested_by(self) -> str:
        """Gets the requested_by of this StatisticsMeta.


        :return: The requested_by of this StatisticsMeta.
        :rtype: str
        """
        return self._requested_by

    @requested_by.setter
    def requested_by(self, requested_by: str):
        """Sets the requested_by of this StatisticsMeta.


        :param requested_by: The requested_by of this StatisticsMeta.
        :type requested_by: str
        """

        self._requested_by = requested_by
