# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatisticsDataCategoriesCategoryBreakdown(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, category: str=None, count: int=None, total_value: float=None):  # noqa: E501
        """StatisticsDataCategoriesCategoryBreakdown - a model defined in Swagger

        :param category: The category of this StatisticsDataCategoriesCategoryBreakdown.  # noqa: E501
        :type category: str
        :param count: The count of this StatisticsDataCategoriesCategoryBreakdown.  # noqa: E501
        :type count: int
        :param total_value: The total_value of this StatisticsDataCategoriesCategoryBreakdown.  # noqa: E501
        :type total_value: float
        """
        self.swagger_types = {
            'category': str,
            'count': int,
            'total_value': float
        }

        self.attribute_map = {
            'category': 'category',
            'count': 'count',
            'total_value': 'total_value'
        }
        self._category = category
        self._count = count
        self._total_value = total_value

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsDataCategoriesCategoryBreakdown':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_data_categories_category_breakdown of this StatisticsDataCategoriesCategoryBreakdown.  # noqa: E501
        :rtype: StatisticsDataCategoriesCategoryBreakdown
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this StatisticsDataCategoriesCategoryBreakdown.


        :return: The category of this StatisticsDataCategoriesCategoryBreakdown.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this StatisticsDataCategoriesCategoryBreakdown.


        :param category: The category of this StatisticsDataCategoriesCategoryBreakdown.
        :type category: str
        """

        self._category = category

    @property
    def count(self) -> int:
        """Gets the count of this StatisticsDataCategoriesCategoryBreakdown.


        :return: The count of this StatisticsDataCategoriesCategoryBreakdown.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this StatisticsDataCategoriesCategoryBreakdown.


        :param count: The count of this StatisticsDataCategoriesCategoryBreakdown.
        :type count: int
        """

        self._count = count

    @property
    def total_value(self) -> float:
        """Gets the total_value of this StatisticsDataCategoriesCategoryBreakdown.


        :return: The total_value of this StatisticsDataCategoriesCategoryBreakdown.
        :rtype: float
        """
        return self._total_value

    @total_value.setter
    def total_value(self, total_value: float):
        """Sets the total_value of this StatisticsDataCategoriesCategoryBreakdown.


        :param total_value: The total_value of this StatisticsDataCategoriesCategoryBreakdown.
        :type total_value: float
        """

        self._total_value = total_value
