# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatisticsDataTopProducts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, sku: str=None, name: str=None, price: float=None, quantity: int=None, total_value: float=None):  # noqa: E501
        """StatisticsDataTopProducts - a model defined in Swagger

        :param id: The id of this StatisticsDataTopProducts.  # noqa: E501
        :type id: int
        :param sku: The sku of this StatisticsDataTopProducts.  # noqa: E501
        :type sku: str
        :param name: The name of this StatisticsDataTopProducts.  # noqa: E501
        :type name: str
        :param price: The price of this StatisticsDataTopProducts.  # noqa: E501
        :type price: float
        :param quantity: The quantity of this StatisticsDataTopProducts.  # noqa: E501
        :type quantity: int
        :param total_value: The total_value of this StatisticsDataTopProducts.  # noqa: E501
        :type total_value: float
        """
        self.swagger_types = {
            'id': int,
            'sku': str,
            'name': str,
            'price': float,
            'quantity': int,
            'total_value': float
        }

        self.attribute_map = {
            'id': 'id',
            'sku': 'sku',
            'name': 'name',
            'price': 'price',
            'quantity': 'quantity',
            'total_value': 'total_value'
        }
        self._id = id
        self._sku = sku
        self._name = name
        self._price = price
        self._quantity = quantity
        self._total_value = total_value

    @classmethod
    def from_dict(cls, dikt) -> 'StatisticsDataTopProducts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Statistics_data_top_products of this StatisticsDataTopProducts.  # noqa: E501
        :rtype: StatisticsDataTopProducts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this StatisticsDataTopProducts.


        :return: The id of this StatisticsDataTopProducts.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this StatisticsDataTopProducts.


        :param id: The id of this StatisticsDataTopProducts.
        :type id: int
        """

        self._id = id

    @property
    def sku(self) -> str:
        """Gets the sku of this StatisticsDataTopProducts.


        :return: The sku of this StatisticsDataTopProducts.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this StatisticsDataTopProducts.


        :param sku: The sku of this StatisticsDataTopProducts.
        :type sku: str
        """

        self._sku = sku

    @property
    def name(self) -> str:
        """Gets the name of this StatisticsDataTopProducts.


        :return: The name of this StatisticsDataTopProducts.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StatisticsDataTopProducts.


        :param name: The name of this StatisticsDataTopProducts.
        :type name: str
        """

        self._name = name

    @property
    def price(self) -> float:
        """Gets the price of this StatisticsDataTopProducts.


        :return: The price of this StatisticsDataTopProducts.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this StatisticsDataTopProducts.


        :param price: The price of this StatisticsDataTopProducts.
        :type price: float
        """

        self._price = price

    @property
    def quantity(self) -> int:
        """Gets the quantity of this StatisticsDataTopProducts.


        :return: The quantity of this StatisticsDataTopProducts.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this StatisticsDataTopProducts.


        :param quantity: The quantity of this StatisticsDataTopProducts.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def total_value(self) -> float:
        """Gets the total_value of this StatisticsDataTopProducts.


        :return: The total_value of this StatisticsDataTopProducts.
        :rtype: float
        """
        return self._total_value

    @total_value.setter
    def total_value(self, total_value: float):
        """Sets the total_value of this StatisticsDataTopProducts.


        :param total_value: The total_value of this StatisticsDataTopProducts.
        :type total_value: float
        """

        self._total_value = total_value
