# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateQuantityRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quantity: int=None, operation: str='set'):  # noqa: E501
        """UpdateQuantityRequest - a model defined in Swagger

        :param quantity: The quantity of this UpdateQuantityRequest.  # noqa: E501
        :type quantity: int
        :param operation: The operation of this UpdateQuantityRequest.  # noqa: E501
        :type operation: str
        """
        self.swagger_types = {
            'quantity': int,
            'operation': str
        }

        self.attribute_map = {
            'quantity': 'quantity',
            'operation': 'operation'
        }
        self._quantity = quantity
        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateQuantityRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateQuantityRequest of this UpdateQuantityRequest.  # noqa: E501
        :rtype: UpdateQuantityRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self) -> int:
        """Gets the quantity of this UpdateQuantityRequest.

        New stock quantity  # noqa: E501

        :return: The quantity of this UpdateQuantityRequest.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this UpdateQuantityRequest.

        New stock quantity  # noqa: E501

        :param quantity: The quantity of this UpdateQuantityRequest.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def operation(self) -> str:
        """Gets the operation of this UpdateQuantityRequest.

        Operation type: - set: Set quantity to exact value - add: Add to current quantity - subtract: Subtract from current quantity   # noqa: E501

        :return: The operation of this UpdateQuantityRequest.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """Sets the operation of this UpdateQuantityRequest.

        Operation type: - set: Set quantity to exact value - add: Add to current quantity - subtract: Subtract from current quantity   # noqa: E501

        :param operation: The operation of this UpdateQuantityRequest.
        :type operation: str
        """
        allowed_values = ["set", "add", "subtract"]  # noqa: E501
        if operation not in allowed_values:
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"
                .format(operation, allowed_values)
            )

        self._operation = operation
