# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateProductRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, category: str=None, brand: str=None, price: float=None, currency: str=None, quantity: int=None, image_url: str=None, status: str=None):  # noqa: E501
        """UpdateProductRequest - a model defined in Swagger

        :param name: The name of this UpdateProductRequest.  # noqa: E501
        :type name: str
        :param description: The description of this UpdateProductRequest.  # noqa: E501
        :type description: str
        :param category: The category of this UpdateProductRequest.  # noqa: E501
        :type category: str
        :param brand: The brand of this UpdateProductRequest.  # noqa: E501
        :type brand: str
        :param price: The price of this UpdateProductRequest.  # noqa: E501
        :type price: float
        :param currency: The currency of this UpdateProductRequest.  # noqa: E501
        :type currency: str
        :param quantity: The quantity of this UpdateProductRequest.  # noqa: E501
        :type quantity: int
        :param image_url: The image_url of this UpdateProductRequest.  # noqa: E501
        :type image_url: str
        :param status: The status of this UpdateProductRequest.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'category': str,
            'brand': str,
            'price': float,
            'currency': str,
            'quantity': int,
            'image_url': str,
            'status': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'category': 'category',
            'brand': 'brand',
            'price': 'price',
            'currency': 'currency',
            'quantity': 'quantity',
            'image_url': 'image_url',
            'status': 'status'
        }
        self._name = name
        self._description = description
        self._category = category
        self._brand = brand
        self._price = price
        self._currency = currency
        self._quantity = quantity
        self._image_url = image_url
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateProductRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateProductRequest of this UpdateProductRequest.  # noqa: E501
        :rtype: UpdateProductRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UpdateProductRequest.

        Product name  # noqa: E501

        :return: The name of this UpdateProductRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UpdateProductRequest.

        Product name  # noqa: E501

        :param name: The name of this UpdateProductRequest.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this UpdateProductRequest.

        Product description  # noqa: E501

        :return: The description of this UpdateProductRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this UpdateProductRequest.

        Product description  # noqa: E501

        :param description: The description of this UpdateProductRequest.
        :type description: str
        """

        self._description = description

    @property
    def category(self) -> str:
        """Gets the category of this UpdateProductRequest.

        Product category  # noqa: E501

        :return: The category of this UpdateProductRequest.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this UpdateProductRequest.

        Product category  # noqa: E501

        :param category: The category of this UpdateProductRequest.
        :type category: str
        """

        self._category = category

    @property
    def brand(self) -> str:
        """Gets the brand of this UpdateProductRequest.

        Product brand  # noqa: E501

        :return: The brand of this UpdateProductRequest.
        :rtype: str
        """
        return self._brand

    @brand.setter
    def brand(self, brand: str):
        """Sets the brand of this UpdateProductRequest.

        Product brand  # noqa: E501

        :param brand: The brand of this UpdateProductRequest.
        :type brand: str
        """

        self._brand = brand

    @property
    def price(self) -> float:
        """Gets the price of this UpdateProductRequest.

        Product price  # noqa: E501

        :return: The price of this UpdateProductRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this UpdateProductRequest.

        Product price  # noqa: E501

        :param price: The price of this UpdateProductRequest.
        :type price: float
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this UpdateProductRequest.

        Currency code  # noqa: E501

        :return: The currency of this UpdateProductRequest.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this UpdateProductRequest.

        Currency code  # noqa: E501

        :param currency: The currency of this UpdateProductRequest.
        :type currency: str
        """

        self._currency = currency

    @property
    def quantity(self) -> int:
        """Gets the quantity of this UpdateProductRequest.

        Stock quantity  # noqa: E501

        :return: The quantity of this UpdateProductRequest.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this UpdateProductRequest.

        Stock quantity  # noqa: E501

        :param quantity: The quantity of this UpdateProductRequest.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def image_url(self) -> str:
        """Gets the image_url of this UpdateProductRequest.

        Product image URL  # noqa: E501

        :return: The image_url of this UpdateProductRequest.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this UpdateProductRequest.

        Product image URL  # noqa: E501

        :param image_url: The image_url of this UpdateProductRequest.
        :type image_url: str
        """

        self._image_url = image_url

    @property
    def status(self) -> str:
        """Gets the status of this UpdateProductRequest.

        Product status  # noqa: E501

        :return: The status of this UpdateProductRequest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this UpdateProductRequest.

        Product status  # noqa: E501

        :param status: The status of this UpdateProductRequest.
        :type status: str
        """
        allowed_values = ["active", "inactive", "discontinued"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
