# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, username: str=None, role: str=None):  # noqa: E501
        """UserInfo - a model defined in Swagger

        :param id: The id of this UserInfo.  # noqa: E501
        :type id: int
        :param username: The username of this UserInfo.  # noqa: E501
        :type username: str
        :param role: The role of this UserInfo.  # noqa: E501
        :type role: str
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'role': str
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'role': 'role'
        }
        self._id = id
        self._username = username
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfo of this UserInfo.  # noqa: E501
        :rtype: UserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this UserInfo.


        :return: The id of this UserInfo.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this UserInfo.


        :param id: The id of this UserInfo.
        :type id: int
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this UserInfo.


        :return: The username of this UserInfo.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserInfo.


        :param username: The username of this UserInfo.
        :type username: str
        """

        self._username = username

    @property
    def role(self) -> str:
        """Gets the role of this UserInfo.


        :return: The role of this UserInfo.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this UserInfo.


        :param role: The role of this UserInfo.
        :type role: str
        """
        allowed_values = ["admin", "user"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role
